### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#24]
When you have the app sit in the background for a while and pull it back up(from in book page) it causes mayday mayday problem when I try to go back to main page where the titles are.

**Comment by anthonyjoeseph** [comment]
in the future it would be better to have a more specific error message, or even a screenshot

**Comment by anthonyjoeseph** [comment]
Should be fixed in upcoming build 1.10 - https://github.com/anthonyjoeseph/Broccoli/commit/e8bc2ff735b263c65502f8edf9301cb9c288743a

However this is difficult to test. @tranquille3000 Please keep an eye out for this bug in the future and re-open this issue if necessary. I think the problem is that aws automatically tries to sign out after an hour. I've added code to refresh the sign-in token, so it shouldn't be an issue, but like I've said, I haven't tested it.
