### ISSUE TITLE
Text board when you are reading a story

### ISSUE THREAD

**Issue by tranquille3000** [anthonyjoeseph/Broccoli#6]
Text boards are up by default when you start reading a book. When you make them go down, it completely disappears. What we need is to have small portion of top part hanging up at the bottom of the screen. 
Also when you have it go away and slide to next page, we need it to make it not come up. -> only up as a default for the first page of the story.

**Comment by anthonyjoeseph** [comment]
Text boards now show their top 25px when dismissed in testflight build 1.4. Please take a look at it - I'm a little hesitant about this feature, since it might appear as though you're supposed to drag the text box up to make it appear.

Please submit a separate issue for the second issue, and please try to keep separate problems as separate issues.
